# Generated by Django 4.2.5 on 2023-09-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_delete_page'),
        ('noticias', '0002_page_delete_noticia'),
    ]

    operations = [
    ]
