# Generated by Django 4.2.5 on 2023-09-30 16:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('union_libre', 'Unión Libre')], max_length=20)),
                ('numero_hijos', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('0', 'Ninguno')], max_length=20)),
                ('estudiante', models.BooleanField(default=False)),
                ('estudios_terminados', models.CharField(choices=[('curso', 'Curso'), ('diplomado', 'Diplomado'), ('tecnica', 'Técnica'), ('tecnologia', 'Tecnología'), ('profesional', 'Profesional'), ('especializacion', 'Especialización'), ('maestria', 'Maestría')], max_length=20)),
                ('eps', models.CharField(choices=[('aliansalud', '1. Aliansalud'), ('cafam', '2. Cafam EPS'), ('capital_salud', '3. Capital Salud EPS'), ('capresoca', '4. Capresoca'), ('colsubsidio', '5. Colsubsidio'), ('comfandi', '6. COMFANDI'), ('compensar', '7. Compensar'), ('coomeva', '8. Coomeva'), ('coosalud', '9. Coosalud'), ('sanitas', '10. EPS Sanitas'), ('sura', '11. EPS Sura'), ('famisanar', '12. Famisanar'), ('medimas', '13. Medimás'), ('mutual_ser', '14. Mutual SER'), ('nueva_eps', '15. Nueva EPS'), ('salud_total', '16. Salud Total'), ('savia_salud', '17. Savia Salud EPS'), ('sisben_IV', '18 SISBEN IV')], max_length=20)),
                ('fondo_pension', models.CharField(choices=[('proteccion', 'Protección'), ('porvenir', 'Porvenir'), ('colfondos', 'Colfondos'), ('old_mutual', 'Old Mutual'), ('colpensiones', 'Colpensiones')], max_length=100)),
                ('fondo_cesantias', models.CharField(choices=[('proteccion', 'Protección'), ('porvenir', 'Porvenir'), ('colfondos', 'Colfondos'), ('old_mutual', 'Old Mutual'), ('colpensiones', 'Colpensiones')], max_length=100)),
                ('banco', models.CharField(choices=[('av_villas', 'AV Villas'), ('banco_de_bogota', 'Banco de Bogotá'), ('banco_de_occidente', 'Banco de Occidente'), ('banco_popular', 'Banco Popular'), ('porvenir', 'Porvenir'), ('bbva', 'BBVA'), ('bancolombia', 'Bancolombia'), ('davivienda', 'Davivienda'), ('banco_santander', 'Banco Santander'), ('banco_agrario', 'Banco Agrario'), ('banco_colpatria', 'Banco Colpatria'), ('credilinea', 'Credilinea')], max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('archivo_certificado_bancario', models.FileField(blank=True, upload_to='archivos_certificados/')),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('termino_fijo', 'Término Fijo'), ('termino_indefinido', 'Término Indefinido'), ('temporal', 'Temporal')], max_length=20)),
                ('duracion_contrato', models.CharField(blank=True, choices=[('3_meses', '3 meses'), ('6_meses', '6 meses'), ('1_anio', '1 año')], max_length=20, null=True)),
                ('correo_empresa', models.EmailField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.EmailField(max_length=100)),
                ('salario_pesos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas_Temporales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_de_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_de_contacto', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa_temporal',
            field=models.ManyToManyField(blank=True, to='pages.empresas_temporales'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_subordinados', to='pages.empleado'),
        ),
    ]
