# Generated by Django 4.2.3 on 2023-08-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_estudio_registroempleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEmpleados2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado')], max_length=20)),
                ('estudiante', models.BooleanField(default=False)),
                ('archivos_cursos', models.FileField(blank=True, upload_to='archivos_cursos/')),
                ('eps', models.CharField(max_length=100)),
                ('fondo_pension', models.CharField(max_length=100)),
                ('fondo_cesantias', models.CharField(max_length=100)),
                ('informacion_financiera', models.TextField()),
                ('archivo_certificado_bancario', models.FileField(blank=True, upload_to='archivos_certificados/')),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('termino_fijo', 'Término Fijo'), ('termino_indefinido', 'Término Indefinido'), ('temporal', 'Temporal')], max_length=20)),
                ('duracion_contrato', models.CharField(max_length=20)),
                ('duracion_contrato1', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('numero_hijos', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (0, 'Ninguno')])),
                ('correo_empresa', models.EmailField(max_length=100)),
                ('correo_personal', models.EmailField(max_length=100)),
                ('salario_pesos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jefe_inmediato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_subordinados', to='pages.registroempleados2')),
            ],
        ),
    ]
