# Generated by Django 4.2.3 on 2023-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_registroempleados2_duracion_contrato1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempleados2',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('union libre', 'Union Libre')], max_length=20),
        ),
    ]
