# Generated by Django 4.2.3 on 2023-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_registroempleados2_empresa_temporal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroempleados2',
            name='empresa_temporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
