# Generated by Django 4.2.3 on 2023-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_empresas_temporales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas_temporales',
            name='direccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresas_temporales',
            name='nombre_de_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresas_temporales',
            name='numero_de_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
