# Generated by Django 4.2.3 on 2023-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_empresas_temporales_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempleados2',
            name='informacion_financiera',
            field=models.TextField(blank=True, null=True),
        ),
    ]
