# Generated by Django 4.2.3 on 2023-08-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_registroempleados2_informacion_financiera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='registroempleados2',
            name='cargo',
            field=models.ManyToManyField(blank=True, to='pages.cargo'),
        ),
    ]
