# Generated by Django 4.2.4 on 2023-08-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_cargo_registroempleados2_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('union_libre', 'Unión Libre')], max_length=20)),
                ('numero_hijos', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('0', 'Ninguno')], max_length=20)),
                ('estudiante', models.BooleanField(default=False)),
                ('estudios_terminados', models.CharField(choices=[('curso', 'Curso'), ('diplomado', 'Diplomado'), ('tecnica', 'Técnica'), ('tecnologia', 'Tecnología'), ('profesional', 'Profesional'), ('especializacion', 'Especialización'), ('maestria', 'Maestría')], max_length=20)),
                ('eps', models.CharField(choices=[('aliansalud', '1. Aliansalud'), ('cafam', '2. Cafam EPS'), ('capital_salud', '3. Capital Salud EPS'), ('capresoca', '4. Capresoca'), ('colsubsidio', '5. Colsubsidio'), ('comfandi', '6. COMFANDI'), ('compensar', '7. Compensar'), ('coomeva', '8. Coomeva'), ('coosalud', '9. Coosalud'), ('sanitas', '10. EPS Sanitas'), ('sura', '11. EPS Sura'), ('famisanar', '12. Famisanar'), ('medimas', '13. Medimás'), ('mutual_ser', '14. Mutual SER'), ('nueva_eps', '15. Nueva EPS'), ('salud_total', '16. Salud Total'), ('savia_salud', '17. Savia Salud EPS'), ('sisben_IV', '18 SISBEN IV')], max_length=20)),
                ('fondo_pension', models.CharField(choices=[('proteccion', 'Protección'), ('porvenir', 'Porvenir'), ('colfondos', 'Colfondos'), ('old_mutual', 'Old Mutual'), ('colpensiones', 'Colpensiones')], max_length=100)),
                ('fondo_cesantias', models.CharField(choices=[('proteccion', 'Protección'), ('porvenir', 'Porvenir'), ('colfondos', 'Colfondos'), ('old_mutual', 'Old Mutual'), ('colpensiones', 'Colpensiones')], max_length=100)),
                ('banco', models.CharField(choices=[('av_villas', 'AV Villas'), ('banco_de_bogota', 'Banco de Bogotá'), ('banco_de_occidente', 'Banco de Occidente'), ('banco_popular', 'Banco Popular'), ('porvenir', 'Porvenir'), ('bbva', 'BBVA'), ('bancolombia', 'Bancolombia'), ('davivienda', 'Davivienda'), ('banco_santander', 'Banco Santander'), ('banco_agrario', 'Banco Agrario'), ('banco_colpatria', 'Banco Colpatria'), ('credilinea', 'Credilinea')], max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('archivo_certificado_bancario', models.FileField(blank=True, upload_to='archivos_certificados/')),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('termino_fijo', 'Término Fijo'), ('termino_indefinido', 'Término Indefinido'), ('temporal', 'Temporal')], max_length=20)),
                ('duracion_contrato', models.CharField(choices=[('1_mes', '1 mes'), ('2_meses', '2 meses'), ('3_meses', '3 meses'), ('4_meses', '4 meses'), ('5_meses', '5 meses'), ('6_meses', '6 meses'), ('7_meses', '7 meses'), ('8_meses', '8 meses'), ('9_meses', '9 meses'), ('10_meses', '10 meses'), ('11_meses', '11 meses'), ('1_anio', '1 año'), ('2_anios', '2 años'), ('3_anios', '3 años'), ('5_anios', '5 años')], max_length=20)),
                ('correo_empresa', models.EmailField(max_length=100)),
                ('correo_personal', models.EmailField(max_length=100)),
                ('salario_pesos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa_temporal', models.ManyToManyField(blank=True, to='pages.empresas_temporales')),
                ('jefe_inmediato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_subordinados', to='pages.empleado')),
            ],
        ),
        migrations.RemoveField(
            model_name='conyugue',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='hijo',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='registroempleados',
            name='estudios_terminados',
        ),
        migrations.RemoveField(
            model_name='registroempleados2',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='registroempleados2',
            name='empresa_temporal',
        ),
        migrations.RemoveField(
            model_name='registroempleados2',
            name='estudios_terminados',
        ),
        migrations.RemoveField(
            model_name='registroempleados2',
            name='jefe_inmediato',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Conyugue',
        ),
        migrations.DeleteModel(
            name='Estudio',
        ),
        migrations.DeleteModel(
            name='Hijo',
        ),
        migrations.DeleteModel(
            name='RegistroEmpleados',
        ),
        migrations.DeleteModel(
            name='RegistroEmpleados2',
        ),
    ]
