# Generated by Django 4.2.5 on 2023-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_hijo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='jefe_inmediato',
            new_name='persona_a_cargo',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='duracion_contrato',
            field=models.CharField(blank=True, choices=[('3_mes', '3 mes'), ('6_meses', '6 meses'), ('12_meses', '12 meses')], max_length=20, null=True),
        ),
    ]
