# Generated by Django 4.2.3 on 2023-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmpleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado')], max_length=20)),
                ('estudiante', models.BooleanField(default=False)),
                ('archivos_cursos', models.FileField(blank=True, upload_to='archivos_cursos/')),
                ('eps', models.CharField(max_length=100)),
                ('fondo_pension', models.CharField(max_length=100)),
                ('fondo_cesantias', models.CharField(max_length=100)),
                ('informacion_financiera', models.TextField()),
                ('archivo_certificado_bancario', models.FileField(blank=True, upload_to='archivos_certificados/')),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('termino_fijo', 'Término Fijo'), ('termino_indefinido', 'Término Indefinido'), ('temporal', 'Temporal')], max_length=20)),
                ('duracion_contrato', models.CharField(max_length=20)),
                ('estudios_terminados', models.ManyToManyField(blank=True, to='pages.estudio')),
            ],
        ),
    ]
