# Generated by Django 4.2.5 on 2023-10-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('union_libre', 'Unión Libre')], max_length=20)),
                ('estudia_actualmente', models.BooleanField(default=False)),
                ('estudios_terminados', models.CharField(choices=[('curso', 'Curso'), ('diplomado', 'Diplomado'), ('tecnica', 'Técnica'), ('tecnologia', 'Tecnología'), ('profesional', 'Profesional'), ('especializacion', 'Especialización'), ('maestria', 'Maestría')], max_length=20)),
                ('nombre_estudio', models.CharField(blank=True, max_length=100, null=True)),
                ('eps', models.CharField(choices=[('aliansalud', '1. Aliansalud'), ('cafam', '2. Cafam EPS'), ('capital_salud', '3. Capital Salud EPS'), ('capresoca', '4. Capresoca'), ('colsubsidio', '5. Colsubsidio'), ('comfandi', '6. COMFANDI'), ('compensar', '7. Compensar'), ('coomeva', '8. Coomeva'), ('coosalud', '9. Coosalud'), ('sanitas', '10. EPS Sanitas'), ('sura', '11. EPS Sura'), ('famisanar', '12. Famisanar'), ('medimas', '13. Medimás'), ('mutual_ser', '14. Mutual SER'), ('nueva_eps', '15. Nueva EPS'), ('salud_total', '16. Salud Total'), ('savia_salud', '17. Savia Salud EPS'), ('sisben_IV', '18 SISBEN IV')], max_length=20)),
                ('fondo_pension', models.CharField(choices=[('proteccion', 'Protección'), ('porvenir', 'Porvenir'), ('colfondos', 'Colfondos'), ('old_mutual', 'Old Mutual'), ('colpensiones', 'Colpensiones')], max_length=100)),
                ('fondo_cesantias', models.CharField(choices=[('proteccion', 'Protección'), ('porvenir', 'Porvenir'), ('colfondos', 'Colfondos'), ('old_mutual', 'Old Mutual'), ('colpensiones', 'Colpensiones')], max_length=100)),
                ('banco', models.CharField(choices=[('av_villas', 'AV Villas'), ('banco_de_bogota', 'Banco de Bogotá'), ('banco_de_occidente', 'Banco de Occidente'), ('banco_popular', 'Banco Popular'), ('porvenir', 'Porvenir'), ('bbva', 'BBVA'), ('bancolombia', 'Bancolombia'), ('davivienda', 'Davivienda'), ('banco_santander', 'Banco Santander'), ('banco_agrario', 'Banco Agrario'), ('banco_colpatria', 'Banco Colpatria'), ('credilinea', 'Credilinea')], max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('archivo_certificado_bancario', models.FileField(blank=True, upload_to='archivos_certificados/')),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('termino_fijo', 'Término Fijo'), ('termino_indefinido', 'Término Indefinido'), ('temporal', 'Temporal')], max_length=20)),
                ('duracion_contrato', models.CharField(blank=True, choices=[('3_meses', '3 meses'), ('6_meses', '6 meses'), ('1_anio', '1 año')], max_length=20, null=True)),
                ('correo_empresa', models.EmailField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.EmailField(max_length=100)),
                ('salario_pesos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiene_personal_a_cargo', models.BooleanField(default=False)),
                ('empresa_temporal', models.ManyToManyField(blank=True, to='pages.empresas_temporales')),
            ],
        ),
    ]
