# Generated by Django 4.2.5 on 2023-10-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_empleado1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado1',
        ),
    ]
