# Generated by Django 4.2.5 on 2023-10-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_empleado1'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='documentos_de_ingreso',
            field=models.FileField(blank=True, upload_to='documentos_de_ingreso/'),
        ),
    ]
