# Generated by Django 4.2.3 on 2023-08-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_hijo_conyugue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroempleados2',
            name='duracion_contrato1',
        ),
        migrations.AddField(
            model_name='registroempleados2',
            name='estudios_terminados',
            field=models.ManyToManyField(blank=True, to='pages.estudio'),
        ),
    ]
