# Generated by Django 4.2.5 on 2023-10-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_empleado_de_quien_depende'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado de empleado'),
        ),
    ]
