# Generated by Django 4.2.5 on 2023-10-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_empleado_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='activo',
        ),
    ]
