# Generated by Django 4.2.3 on 2023-08-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_registroempleados2_empresa_temporal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroempleados2',
            name='empresa_temporal',
        ),
        migrations.AlterField(
            model_name='registroempleados2',
            name='duracion_contrato',
            field=models.CharField(max_length=20),
        ),
    ]
