# Generated by Django 4.2.5 on 2023-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_empleado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado_del_empleado',
            field=models.BooleanField(default=True),
        ),
    ]
