# Generated by Django 4.2.5 on 2023-10-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_empleado_estado_del_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='estado_del_empleado',
            new_name='empleado_activo',
        ),
    ]
