# Generated by Django 4.2.3 on 2023-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_registroempleados2_empresa_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempleados2',
            name='duracion_contrato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
