# Generated by Django 4.2.3 on 2023-08-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_registroempleados2_duracion_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas_Temporales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='registroempleados2',
            name='empresa_temporal',
        ),
        migrations.AddField(
            model_name='registroempleados2',
            name='empresa_temporal',
            field=models.ManyToManyField(blank=True, to='pages.empresas_temporales'),
        ),
    ]
