# Generated by Django 4.2.5 on 2023-10-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_hijo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='jefe_inmediato',
            new_name='persona_a_cargo',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='duracion_contrato',
            field=models.CharField(blank=True, choices=[('3_meses', '3 meses'), ('6_meses', '6 meses'), ('1_anio', '1 año')], max_length=20, null=True),
        ),
    ]
