# Generated by Django 4.2.5 on 2023-09-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0002_ticketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('INP', 'In Progress'), ('D', 'Done'), ('INV', 'Invalid'), ('APR', 'Approved'), ('DEN', 'Denied')], default='N', max_length=3),
        ),
    ]
