# Generated by Django 4.2.5 on 2023-10-02 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0006_remove_ticketmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
