# Generated by Django 4.2.5 on 2023-10-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0009_ticketmodel_fue_completado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='fue_completado',
        ),
    ]
